version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - MQTT_TOPICS=Extractions
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro